import Head from 'next/head'
import Image from 'next/image'
import React, { useContext } from 'react'
import { useRouter } from 'next/router'
import AnchorLink from './AnchorLink'
import Button from './Button'
import { AuthContext } from './Context'
import Logo from './Logo'
import Navigation from './Navigation'

function Layout({ children }) {
    const { user } = useContext(AuthContext)
    const router = useRouter()
    
    if (user) {
        return (
            <>
                <Navigation />
                {children}
            </>
        )
    }


    return router.asPath === "/authentication" ? (
        <>
            {children}
        </>
    ) : (
        <div className='w-full h-screen bg-gray-300/30' >
            <Head>
                <title>Welcome</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full h-full flex flex-col justify-center items-center p-10 relative' >
                <div className='w-full h-fit text-center flex flex-col justify-center items-center gap-5' >
                    <Logo />
                    <h6 className='font-semibold text-gray-500' >
                        Aquatec Website Dashboard
                    </h6>
                    <h3 className='font-bold'>
                        Edit all text and Images of your website
                    </h3>
                    <AnchorLink route="/authentication">
                        <Button style="primary-btn" >
                            Get Started
                        </Button>
                    </AnchorLink>
                    <div className='w-full h-40vh relative rounded-md overflow-hidden' >
                        <Image src='/project-pics/landing.png' layout='fill' alt='Pharmacy Landing Page' className='object-contain' />
                    </div>
                </div>
            </main>
        </div>
    )
}


export default Layout