import Head from 'next/head'
import React, { useContext, useEffect } from 'react'
import { NavContext, SectionsContext } from '../src/Components/Context'
import EditCard from '../src/Components/EditCard'

function Home() {

  const [page, setPage] = useContext(NavContext)
  const [sections] = useContext(SectionsContext)
  

  useEffect(() => {
    if (page === "Home") return;
    setPage("Home")
    console.log(sections)
  }, [])


  return (
    <div className='pt-20' >
      <Head>
        <title>Aquatec | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/logo.png" />
      </Head>
      {
        sections.map((section, index) => (
          <section key={`${index} ${section}`} >
            <h3>
              {section}
            </h3>
            <EditCard document={section} collection="Home" key={section} />
          </section>
        ))
      }
    </div>
  )
}

export default Home